In [1]:
import numpy as np

In [2]:
list_of_lists =[]
with open('day4test.txt') as f:
    for line in f:
        inner_list = [elt.strip() for elt in line.split()]
        list_of_lists.append(inner_list)

In [3]:
input_numbers = list_of_lists[0]
#List of input numbers
input_list = input_numbers[0].split(',')
input_list

['7',
 '4',
 '9',
 '5',
 '11',
 '17',
 '23',
 '2',
 '0',
 '14',
 '21',
 '24',
 '10',
 '16',
 '13',
 '6',
 '15',
 '25',
 '12',
 '22',
 '18',
 '20',
 '8',
 '19',
 '3',
 '26',
 '1']

In [4]:
#List of lists containing the matrices.
matrices = list_of_lists[2:]

In [5]:
number_of_matrices = int((len(list_of_lists) - 1) / 6)
number_of_matrices

3

In [252]:
def win_check (matrix):
    for i in range(matrix.shape[0]):
        if np.all(matrix[i] == matrix[i][0]):
            print('win')
        break
        trans_mat = matrix.T        
        for i in range(trans_mat.shape[0]):
            if np.all(trans_mat[i] == trans_mat[i][0]):
                print('win')
            break     

#Where does win_check go, it never wor

In [254]:
list_of_matrices = np.zeros((number_of_matrices,5,5),dtype=int)

count_index = 0
count_matrix = 0
while count_matrix <= number_of_matrices - 1:
    list_of_matrices[count_matrix] = matrices[count_index:count_index + 5]
    count_index += 6
    count_matrix +=1
    
for input_number in input_list:
    for m, matrix in enumerate(list_of_matrices):
        for i,row in enumerate(matrix):
            for j, value in enumerate(row):
                if value.astype(str) == input_number:
                    list_of_matrices[m][i][j] = 100
                else:
                    pass
                print(list_of_matrices)
                
                
        
                
    #for m, matrix in enumerate(list_of_matrices):
                #if  all(list_of_matrices[m][i]==100) or all(list_of_matrices[m][j]==100):
                #if   all(list_of_matrices[m][j]==100):
                                    

[[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
[[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
[[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
[[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13

  [  2   0  12   3 100]]]
[[[ 22  13 100 100   0]
  [  8   2  23 100  24]
  [ 21 100  14  16 100]
  [  6  10   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15   0   2  22]
  [100  18  13 100 100]
  [ 19   8 100  25  23]
  [ 20 100  10  24 100]
  [ 14  21  16  12   6]]

 [[ 14  21 100  24 100]
  [ 10  16  15 100  19]
  [ 18   8  23  26  20]
  [ 22 100  13   6 100]
  [  2   0  12   3 100]]]
[[[ 22  13 100 100   0]
  [  8   2  23 100  24]
  [ 21 100  14  16 100]
  [  6  10   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15   0   2  22]
  [100  18  13 100 100]
  [ 19   8 100  25  23]
  [ 20 100  10  24 100]
  [ 14  21  16  12   6]]

 [[ 14  21 100  24 100]
  [ 10  16  15 100  19]
  [ 18   8  23  26  20]
  [ 22 100  13   6 100]
  [  2   0  12   3 100]]]
[[[ 22  13 100 100   0]
  [  8   2  23 100  24]
  [ 21 100  14  16 100]
  [  6  10   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15   0   2  22]
  [100  18  13 100 100]
  [ 19   8 100  25  23]
  [ 20 100  10  24 100]
  [ 14  21  16  12   6]]

  [100 100  12   3 100]]]
[[[ 22  13 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [  6 100   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15 100 100  22]
  [100  18  13 100 100]
  [ 19   8 100  25 100]
  [ 20 100 100 100 100]
  [100 100 100  12   6]]

 [[100 100 100 100 100]
  [100 100  15 100  19]
  [ 18   8 100  26  20]
  [ 22 100  13   6 100]
  [100 100  12   3 100]]]
[[[ 22  13 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [  6 100   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15 100 100  22]
  [100  18  13 100 100]
  [ 19   8 100  25 100]
  [ 20 100 100 100 100]
  [100 100 100  12   6]]

 [[100 100 100 100 100]
  [100 100  15 100  19]
  [ 18   8 100  26  20]
  [ 22 100  13   6 100]
  [100 100  12   3 100]]]
[[[ 22  13 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [  6 100   3  18 100]
  [  1  12  20  15  19]]

 [[  3  15 100 100  22]
  [100  18  13 100 100]
  [ 19   8 100  25 100]
  [ 20 100 100 100 100]
  [100 100 100  12   6]]

  [100 100 100   3 100]]]
[[[100 100 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [100 100   3  18 100]
  [  1 100  20 100  19]]

 [[  3 100 100 100 100]
  [100  18 100 100 100]
  [ 19   8 100 100 100]
  [ 20 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100  19]
  [ 18   8 100  26  20]
  [ 22 100 100 100 100]
  [100 100 100   3 100]]]
[[[100 100 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [100 100   3  18 100]
  [  1 100  20 100  19]]

 [[  3 100 100 100 100]
  [100  18 100 100 100]
  [ 19   8 100 100 100]
  [ 20 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100  19]
  [ 18   8 100  26  20]
  [ 22 100 100 100 100]
  [100 100 100   3 100]]]
[[[100 100 100 100 100]
  [  8 100 100 100 100]
  [100 100 100 100 100]
  [100 100   3  18 100]
  [  1 100  20 100  19]]

 [[  3 100 100 100 100]
  [100  18 100 100 100]
  [ 19   8 100 100 100]
  [ 20 100 100 100 100]
  [100 100 100 100 100]]

  [100 100 100 100 100]]]
[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [  1 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100  26 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]
[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [  1 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100  26 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]
[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [  1 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

# ignore 

In [207]:
#Convert first column and row to 1 for testing
list_of_matrices[0][0] = 1
#list_of_matrices[0].T[0] = 0

In [192]:
matrix = list_of_matrices[0]

In [179]:
matrix

array([[ 1,  1,  1,  1,  1],
       [ 0,  2, 23,  4, 24],
       [ 0,  9, 14, 16,  7],
       [ 0, 10,  3, 18,  5],
       [ 0, 12, 20, 15, 19]])

In [181]:
range(matrix.shape[0])

range(0, 5)

In [213]:
def win_check (matrix):
for i in range(matrix.shape[0]):
    if np.all(matrix[i] == matrix[i][0]):
        print ('row', i)
        break
trans_mat = matrix.T        
for i in range(trans_mat.shape[0]):
    if np.all(trans_mat[i] == trans_mat[i][0]):
        print('column', i)
        break

row 0


In [108]:
list_of_matrices[0][4]

array([100, 100,  20,  15,  19])

In [151]:
np.ravel(list_of_matrices[0])

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [81]:
#Iterating through all of the rows/columns if a value on the input list is met then the matrix is updated to True
#We need to test after each update it either all of the row or all of the column is true.
for input_number in input_list:
    for i , row in enumerate(matrices):
        for j, value in enumerate(row):
            if all(matrices[i]==100) or all(matrices[j]==100):
                break

TypeError: 'bool' object is not iterable

In [72]:
list_of_matrices

array([[[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]],

       [[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]],

       [[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]]])

In [30]:
list_of_matrices

array([[[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]],

       [[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]],

       [[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]]])

In [31]:
#Iterating through all of the rows/columns if a value on the input list is met then the matrix is updated to True
#We need to test after each update it either all of the row or all of the column is true.
for input_number in input_list:
    for i , row in enumerate(matrices):
        for j, value in enumerate(row):
            if value == input_number:
                matrices[i][j] = True
            else:
                pass
            if all(matrices[i]) or all(matrices[j]):
                break

In [32]:
matrices

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19'],
 [],
 [True, '15', '0', '2', '22'],
 [True, '18', '13', '17', '5'],
 [True, '8', '7', '25', '23'],
 [True, '11', '10', '24', '4'],
 [True, '21', '16', '12', '6'],
 [],
 [True, '21', '17', '24', '4'],
 [True, '16', '15', '9', '19'],
 [True, '8', '23', '26', '20'],
 [True, '11', '13', '6', '5'],
 [True, '0', '12', '3', '7']]

# Scratch section

In [251]:
for i , row in enumerate(matrices):
    for j, value in enumerate(row):
        print(value)
      

22
13
17
11
0
8
2
23
4
24
21
9
14
16
7
6
10
3
18
5
1
12
20
15
19
3
15
0
2
22
9
18
13
17
5
19
8
7
25
23
20
11
10
24
4
14
21
16
12
6
14
21
17
24
4
10
16
15
9
19
18
8
23
26
20
22
11
13
6
5
2
0
12
3
7


In [252]:
#Iterating through all of the rows/columns if a value on the input list is met then the matrix is updated to True
#We need to test after each update it either all of the row or all of the column is true.
for input_number in input_list:
    for i , row in enumerate(matrices):
        for j, value in enumerate(row):
            if value == input_number:
                matrices[i][j] = True
            else:
                pass
            if all(matrices[i]) or all(matrices[j]):
                break

In [29]:
matrices

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [61]:
list_of_matrices[0] = 1

In [62]:
list_of_matrices[1] = 2

In [63]:
list_of_matrices[2] = 3

In [64]:
list_of_matrices

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

In [79]:
matrices

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [67]:
matrices[0:5]

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [78]:
matrices[6:11]

[['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6']]

In [47]:
x = []
for x in list_of_matrices:
    x.append(x)
      

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [34]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
list_of_matrices[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [256]:
matrices[0:5]

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19']]

In [257]:
list_of_matrices

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [53]:
matrices[0:5]

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [89]:
count_index = 0
count_matrix = 0
for matrix in list_of_matrices:
    matrix = matrices[count_index:count_index + 5]
    list_of_matrices[count_matrix] = matrix
    count_index = count_index + 5
    count_matrix = count_matrix + 1
    print(count)

5


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [86]:
matrix

[['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 []]

In [85]:
list_of_matrices

array([[[22., 13., 17., 11.,  0.],
        [ 8.,  2., 23.,  4., 24.],
        [21.,  9., 14., 16.,  7.],
        [ 6., 10.,  3., 18.,  5.],
        [ 1., 12., 20., 15., 19.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [81]:
matrix

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [82]:
list_of_matrices

array([[[22., 13., 17., 11.,  0.],
        [ 8.,  2., 23.,  4., 24.],
        [21.,  9., 14., 16.,  7.],
        [ 6., 10.,  3., 18.,  5.],
        [ 1., 12., 20., 15., 19.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [66]:
count = 0
for matrix in list_of_matrices:
    list_of_matrices[count] = matrices[count:count + 5]
    count = count + 1 

In [67]:
list_of_matrices

[[['22', '13', '17', '11', '0'],
  ['8', '2', '23', '4', '24'],
  ['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19']],
 [['8', '2', '23', '4', '24'],
  ['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  []],
 [['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22']],
 [['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22'],
  ['9', '18', '13', '17', '5']],
 [['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22'],
  ['9', '18', '13', '17', '5'],
  ['19', '8', '7', '25', '23']]]

In [46]:
for x in list_of_matrices:
    print(x[0])

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [41]:
for mat_num, matrix in enumerate(list_of_matrices):
    #matrix[mat_num - 1] = matrices[mat_num:mat_num + 5]
    #a = matrix[mat_num]
    print(list(enumerate(list_of_matrices)))
    #print(mat_num)
    #print(matrix[mat_num])
    #print(matrices[mat_num:(mat_num + 5)])

[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (1, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (2, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]]))]
[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (1, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (2, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]]))]
[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.,

In [40]:
a

array([0., 0., 0., 0., 0.])

In [38]:
for matrix in list_of_matrices:
    print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
list_of_matrices[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
list_of_matrices[0:]

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [259]:
matrices

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19'],
 [],
 [True, '15', '0', '2', '22'],
 [True, '18', '13', '17', '5'],
 [True, '8', '7', '25', '23'],
 [True, '11', '10', '24', '4'],
 [True, '21', '16', '12', '6'],
 [],
 [True, '21', '17', '24', '4'],
 [True, '16', '15', '9', '19'],
 [True, '8', '23', '26', '20'],
 [True, '11', '13', '6', '5'],
 [True, '0', '12', '3', '7']]

In [260]:
list_of_matrices[0] = matrices[0:5]

In [261]:
list_of_matrices[1] = matrices[6:11]

In [262]:
list_of_matrices[2] = matrices[12:17]

In [263]:
input_numbers = list_of_lists[0]

In [264]:
input_numbers

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [265]:
test = list_of_lists[2]

In [266]:
len(list_of_lists)

19

In [267]:
#Each matrix requires 6 entries in the list. 1 blank entry & 5 rows of numbers.
#Total number of matrices is length of the list, - 1 for the input numbers
# Divided by 6
number_of_matrices = (len(mylist) - 1) / 6 
number_of_matrices

3.0

In [268]:
for i,row in enumerate(list_of_lists):
    print(row)

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']
[]
[True, '13', '17', '11', '0']
[True, '2', '23', '4', '24']
[True, '9', '14', '16', '7']
[True, '10', '3', '18', '5']
[True, '12', '20', '15', '19']
[]
[True, '15', '0', '2', '22']
[True, '18', '13', '17', '5']
[True, '8', '7', '25', '23']
[True, '11', '10', '24', '4']
[True, '21', '16', '12', '6']
[]
[True, '21', '17', '24', '4']
[True, '16', '15', '9', '19']
[True, '8', '23', '26', '20']
[True, '11', '13', '6', '5']
[True, '0', '12', '3', '7']


In [269]:
list_of_lists[0]

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [270]:
list_of_lists[0]

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [271]:
mylist

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [272]:
input_numbers = mylist[0]

In [273]:
input_numbers

'7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'

In [274]:
#Each matrix requires 6 entries in the list. 1 blank entry & 5 rows of numbers.
#Total number of matrices is length of the list, - 1 for the input numbers
# Divided by 6
number_of_matrices = (len(mylist) - 1) / 6 

In [275]:
number_of_matrices

3.0

In [276]:
mylist[2]

'22 13 17 11  0'

In [ ]:
input_list = input_numbers[0].split(',')

In [8]:
import numpy as np

In [1]:
list_of_lists =[]
with open('day4test.txt') as f:
    for line in f:
        inner_list = [elt.strip() for elt in line.split()]
        list_of_lists.append(inner_list)

In [91]:
list_of_lists =[]
with open('day4test.txt') as f:
    file = f.read()


In [3]:
input_numbers = list_of_lists[0]
input_list = input_numbers[0].split(',')

In [4]:
input_list

['7',
 '4',
 '9',
 '5',
 '11',
 '17',
 '23',
 '2',
 '0',
 '14',
 '21',
 '24',
 '10',
 '16',
 '13',
 '6',
 '15',
 '25',
 '12',
 '22',
 '18',
 '20',
 '8',
 '19',
 '3',
 '26',
 '1']

In [6]:
list_of_lists

[['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'],
 [],
 ['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [12]:
matrices = list_of_lists[2:]

In [14]:
matrices[0:5]

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [138]:
board = []

In [141]:
for line in open('day4test.txt'):
    line = line.strip()
    numbers = line.split(',')
    board.append(line.split())

In [142]:
board

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19',
 '',
 '3 15  0  2 22',
 '9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 '2  0 12  3  7',
 ['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'],
 [],
 ['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [133]:
line

'2  0 12  3  7'

In [135]:
numbers

['2  0 12  3  7']