In [1]:
import numpy as np

In [2]:
list_of_lists =[]
with open('day4test.txt') as f:
    for line in f:
        inner_list = [elt.strip() for elt in line.split()]
        list_of_lists.append(inner_list)

In [3]:
input_numbers = list_of_lists[0]
#List of input numbers
input_list = input_numbers[0].split(',')
input_list

['7',
 '4',
 '9',
 '5',
 '11',
 '17',
 '23',
 '2',
 '0',
 '14',
 '21',
 '24',
 '10',
 '16',
 '13',
 '6',
 '15',
 '25',
 '12',
 '22',
 '18',
 '20',
 '8',
 '19',
 '3',
 '26',
 '1']

In [4]:
#List of lists containing the matrices.
matrices = list_of_lists[2:]

In [6]:
number_of_matrices = int((len(list_of_lists) - 1) / 6)
number_of_matrices

3

In [248]:
matrices

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [249]:
print(list(enumerate(matrices[0])))

[(0, '22'), (1, '13'), (2, '17'), (3, '11'), (4, '0')]


In [250]:
input_list

['7',
 '4',
 '9',
 '5',
 '11',
 '17',
 '23',
 '2',
 '0',
 '14',
 '21',
 '24',
 '10',
 '16',
 '13',
 '6',
 '15',
 '25',
 '12',
 '22',
 '18',
 '20',
 '8',
 '19',
 '3',
 '26',
 '1']

In [251]:
for i , row in enumerate(matrices):
    for j, value in enumerate(row):
        print(value)
      

22
13
17
11
0
8
2
23
4
24
21
9
14
16
7
6
10
3
18
5
1
12
20
15
19
3
15
0
2
22
9
18
13
17
5
19
8
7
25
23
20
11
10
24
4
14
21
16
12
6
14
21
17
24
4
10
16
15
9
19
18
8
23
26
20
22
11
13
6
5
2
0
12
3
7


In [252]:
#Iterating through all of the rows/columns if a value on the input list is met then the matrix is updated to True
#We need to test after each update it either all of the row or all of the column is true.
for input_number in input_list:
    for i , row in enumerate(matrices):
        for j, value in enumerate(row):
            if value == input_number:
                matrices[i][j] = True
            else:
                pass
            if all(matrices[i]) or all(matrices[j]):
                break

In [7]:
matrices

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 [],
 ['3', '15', '0', '2', '22'],
 ['9', '18', '13', '17', '5'],
 ['19', '8', '7', '25', '23'],
 ['20', '11', '10', '24', '4'],
 ['14', '21', '16', '12', '6'],
 [],
 ['14', '21', '17', '24', '4'],
 ['10', '16', '15', '9', '19'],
 ['18', '8', '23', '26', '20'],
 ['22', '11', '13', '6', '5'],
 ['2', '0', '12', '3', '7']]

In [69]:
list_of_matrices = np.zeros((number_of_matrices,5,5))

In [70]:
list_of_matrices

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [255]:
matrices

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19'],
 [],
 [True, '15', '0', '2', '22'],
 [True, '18', '13', '17', '5'],
 [True, '8', '7', '25', '23'],
 [True, '11', '10', '24', '4'],
 [True, '21', '16', '12', '6'],
 [],
 [True, '21', '17', '24', '4'],
 [True, '16', '15', '9', '19'],
 [True, '8', '23', '26', '20'],
 [True, '11', '13', '6', '5'],
 [True, '0', '12', '3', '7']]

In [256]:
matrices[0:5]

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19']]

In [257]:
list_of_matrices

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [53]:
matrices[0:5]

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [89]:
count_index = 0
count_matrix = 0
for matrix in list_of_matrices:
    matrix = matrices[count_index:count_index + 5]
    list_of_matrices[count_matrix] = matrix
    count_index = count_index + 5
    count_matrix = count_matrix + 1
    print(count)

5


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [86]:
matrix

[['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19'],
 []]

In [85]:
list_of_matrices

array([[[22., 13., 17., 11.,  0.],
        [ 8.,  2., 23.,  4., 24.],
        [21.,  9., 14., 16.,  7.],
        [ 6., 10.,  3., 18.,  5.],
        [ 1., 12., 20., 15., 19.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [81]:
matrix

[['22', '13', '17', '11', '0'],
 ['8', '2', '23', '4', '24'],
 ['21', '9', '14', '16', '7'],
 ['6', '10', '3', '18', '5'],
 ['1', '12', '20', '15', '19']]

In [82]:
list_of_matrices

array([[[22., 13., 17., 11.,  0.],
        [ 8.,  2., 23.,  4., 24.],
        [21.,  9., 14., 16.,  7.],
        [ 6., 10.,  3., 18.,  5.],
        [ 1., 12., 20., 15., 19.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [66]:
count = 0
for matrix in list_of_matrices:
    list_of_matrices[count] = matrices[count:count + 5]
    count = count + 1 

In [67]:
list_of_matrices

[[['22', '13', '17', '11', '0'],
  ['8', '2', '23', '4', '24'],
  ['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19']],
 [['8', '2', '23', '4', '24'],
  ['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  []],
 [['21', '9', '14', '16', '7'],
  ['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22']],
 [['6', '10', '3', '18', '5'],
  ['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22'],
  ['9', '18', '13', '17', '5']],
 [['1', '12', '20', '15', '19'],
  [],
  ['3', '15', '0', '2', '22'],
  ['9', '18', '13', '17', '5'],
  ['19', '8', '7', '25', '23']]]

In [46]:
for x in list_of_matrices:
    print(x[0])

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [41]:
for mat_num, matrix in enumerate(list_of_matrices):
    #matrix[mat_num - 1] = matrices[mat_num:mat_num + 5]
    #a = matrix[mat_num]
    print(list(enumerate(list_of_matrices)))
    #print(mat_num)
    #print(matrix[mat_num])
    #print(matrices[mat_num:(mat_num + 5)])

[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (1, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (2, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]]))]
[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (1, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])), (2, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]]))]
[(0, array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.,

In [40]:
a

array([0., 0., 0., 0., 0.])

In [38]:
for matrix in list_of_matrices:
    print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
list_of_matrices[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
list_of_matrices[0:]

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [259]:
matrices

[[True, '13', '17', '11', '0'],
 [True, '2', '23', '4', '24'],
 [True, '9', '14', '16', '7'],
 [True, '10', '3', '18', '5'],
 [True, '12', '20', '15', '19'],
 [],
 [True, '15', '0', '2', '22'],
 [True, '18', '13', '17', '5'],
 [True, '8', '7', '25', '23'],
 [True, '11', '10', '24', '4'],
 [True, '21', '16', '12', '6'],
 [],
 [True, '21', '17', '24', '4'],
 [True, '16', '15', '9', '19'],
 [True, '8', '23', '26', '20'],
 [True, '11', '13', '6', '5'],
 [True, '0', '12', '3', '7']]

In [260]:
list_of_matrices[0] = matrices[0:5]

In [261]:
list_of_matrices[1] = matrices[6:11]

In [262]:
list_of_matrices[2] = matrices[12:17]

In [263]:
input_numbers = list_of_lists[0]

In [264]:
input_numbers

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [265]:
test = list_of_lists[2]

In [266]:
len(list_of_lists)

19

In [267]:
#Each matrix requires 6 entries in the list. 1 blank entry & 5 rows of numbers.
#Total number of matrices is length of the list, - 1 for the input numbers
# Divided by 6
number_of_matrices = (len(mylist) - 1) / 6 
number_of_matrices

3.0

In [268]:
for i,row in enumerate(list_of_lists):
    print(row)

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']
[]
[True, '13', '17', '11', '0']
[True, '2', '23', '4', '24']
[True, '9', '14', '16', '7']
[True, '10', '3', '18', '5']
[True, '12', '20', '15', '19']
[]
[True, '15', '0', '2', '22']
[True, '18', '13', '17', '5']
[True, '8', '7', '25', '23']
[True, '11', '10', '24', '4']
[True, '21', '16', '12', '6']
[]
[True, '21', '17', '24', '4']
[True, '16', '15', '9', '19']
[True, '8', '23', '26', '20']
[True, '11', '13', '6', '5']
[True, '0', '12', '3', '7']


In [269]:
list_of_lists[0]

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [270]:
list_of_lists[0]

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1']

In [271]:
mylist

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [272]:
input_numbers = mylist[0]

In [273]:
input_numbers

'7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'

In [274]:
#Each matrix requires 6 entries in the list. 1 blank entry & 5 rows of numbers.
#Total number of matrices is length of the list, - 1 for the input numbers
# Divided by 6
number_of_matrices = (len(mylist) - 1) / 6 

In [275]:
number_of_matrices

3.0

In [276]:
mylist[2]

'22 13 17 11  0'